export type Coin = {
    id: string,
    symbol: string,
    image: string,
    current_price: number,
    market_cap: number,
    price_change_percentage_24h: number,
    price_change_24h: number,
    price_change_percentage_7d_in_currency: number,
    price_change_percentage_30d_in_currency: number,
    price_change_percentage_1y_in_currency: number,
    circulating_supply: number,
    market_cap_rank: number,
    ath: number,
    atl: number,
    total_volume: number,
    high_24h: number,
    low_24h: number,
    fully_diluted_valuation: number
} 
